### ISSUE TITLE
Confusion regarding the multiplication used

### ISSUE THREAD

**Issue by shivanshu-sahoo** [debtanu09/fmultiplier#1]
I was going through your code for the implementation of IEEE 754 floatingpoint multiplier. I noticed that you used `z_e <= a_e + b_e + 1; product <= a_m * b_m * 4;` but I was bit confused as I think the code should be  `z_e <= a_e + b_e + 127; product <= a_m * b_m ;`. But your syntax gives the correct answer but mine does not. Can you explain the logic behind using it?

**Comment by debtanu09** [comment]
Hi, I've already subtracted 127 from both a_e and b_e beforehand (line 52 and 53) so I'm just adding 1 to get the correct exponent by removing the bias of 127. Also, I'm multiplying by 4 to left-shift the product by 2 bits whose significance you can see later on in the code in rounding and normalizing and/or the exponent depending on the mantissa.
